service: developers

params:
  default:
    domain: developers-${sls:stage}.examplary.ai
  production:
    domain: developers.examplary.ai

provider:
  name: aws
  region: eu-central-1
  stage: ${opt:stage, 'dev'}
  deploymentMethod: direct

plugins:
  - serverless-lift

constructs:
  developers:
    type: static-website
    path: build
    domain: ${param:domain}
    certificate: ${env:ACM_CERTIFICATE_ARN}

resources:
  Resources:
    Route53Record:
      Type: AWS::Route53::RecordSet
      Properties:
        HostedZoneId: Z06296911GDFSE5PQZR2Z
        Name: ${param:domain}
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName: ${construct:developers.cname}
